"""Update model

Revision ID: 07db398a07bc
Revises: 139e8fe81a52
Create Date: 2025-02-22 15:12:28.421792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07db398a07bc'
down_revision = '139e8fe81a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('current_term',
               existing_type=mysql.ENUM('First', 'Second', 'Third'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('current_term',
               existing_type=mysql.ENUM('First', 'Second', 'Third'),
               nullable=True)

    # ### end Alembic commands ###
