"""Creating models

Revision ID: 138430340c9a
Revises: 
Create Date: 2024-06-04 02:05:31.383343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138430340c9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('parent_phone_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('parent_occupation', sa.String(length=100), nullable=False),
    sa.Column('entry_class', sa.String(length=50), nullable=False),
    sa.Column('previous_class', sa.String(length=50), nullable=True),
    sa.Column('state_of_origin', sa.String(length=50), nullable=False),
    sa.Column('local_government_area', sa.String(length=50), nullable=False),
    sa.Column('religion', sa.String(length=50), nullable=False),
    sa.Column('date_registered', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_assessment', sa.Integer(), nullable=False),
    sa.Column('summative_test', sa.Integer(), nullable=False),
    sa.Column('exam', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=False),
    sa.Column('session', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('student')
    op.drop_table('user')
    op.drop_table('subject')
    # ### end Alembic commands ###
