"""Update user models

Revision ID: 269e722ab7db
Revises: 08bb1bb606af
Create Date: 2024-05-13 23:18:02.890768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269e722ab7db'
down_revision = '08bb1bb606af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
