"""Update Models

Revision ID: 4b5f3e0819da
Revises: 5942c3641a59
Create Date: 2024-06-03 09:00:06.014719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5f3e0819da'
down_revision = '5942c3641a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('remark', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('remark')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
