"""update models

Revision ID: 5942c3641a59
Revises: 01bb35743cd9
Create Date: 2024-05-29 03:50:34.100831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5942c3641a59'
down_revision = '01bb35743cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_assessment', sa.Integer(), nullable=False),
    sa.Column('summative_test', sa.Integer(), nullable=False),
    sa.Column('exam', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=False),
    sa.Column('session', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('score', mysql.FLOAT(), nullable=False),
    sa.Column('grade', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('term', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('session', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='result_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('score')
    op.drop_table('subject')
    # ### end Alembic commands ###
