"""Update model

Revision ID: 7e355402f54c
Revises: d506be8a2feb
Create Date: 2025-03-02 14:23:04.544162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e355402f54c'
down_revision = 'd506be8a2feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_privilege', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_manage_subjects', sa.Boolean(), nullable=True))

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('admin_privilege', schema=None) as batch_op:
        batch_op.drop_column('can_manage_subjects')

    # ### end Alembic commands ###
