"""Add session_id and term to class_teacher

Revision ID: b9f49678448d
Revises: 0ad43290c67c
Create Date: 2025-03-09 20:05:47.220910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9f49678448d'
down_revision = '0ad43290c67c'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('result_old', schema=None) as batch_op:
    #     batch_op.drop_index('unique_result')

    # op.drop_table('result_old')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('result_old',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('subject_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('term', mysql.ENUM('First', 'Second', 'Third'), nullable=False),
    # sa.Column('session', mysql.VARCHAR(length=20), nullable=False),
    # sa.Column('class_assessment', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('summative_test', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('exam', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('total', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('grade', mysql.VARCHAR(length=5), nullable=True),
    # sa.Column('remark', mysql.VARCHAR(length=100), nullable=True),
    # sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.Column('next_term_begins', mysql.VARCHAR(length=100), nullable=True),
    # sa.Column('last_term_average', mysql.FLOAT(), nullable=True),
    # sa.Column('position', mysql.VARCHAR(length=10), nullable=True),
    # sa.Column('date_issued', mysql.VARCHAR(length=100), nullable=True),
    # sa.Column('subjects_offered', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('grand_total', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('term_average', mysql.FLOAT(), nullable=True),
    # sa.Column('cumulative_average', mysql.FLOAT(), nullable=True),
    # sa.Column('principal_remark', mysql.VARCHAR(length=100), nullable=True),
    # sa.Column('teacher_remark', mysql.VARCHAR(length=100), nullable=True),
    # sa.Column('class_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='fk_result_class_id'),
    # sa.ForeignKeyConstraint(['session_id'], ['session.id'], name='fk_result_session_id'),
    # sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='result_old_ibfk_1'),
    # sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='result_old_ibfk_2'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_default_charset='utf8mb3',
    # mysql_engine='InnoDB'
    # )
    # with op.batch_alter_table('result_old', schema=None) as batch_op:
    #     batch_op.create_index('unique_result', ['student_id', 'subject_id', 'term', 'session'], unique=True)

    # ### end Alembic commands ###
