"""Add ON DELETE CASCADE to foreign keys

Revision ID: d8c5de272a73
Revises: 2822e0b9b0ed
Create Date: 2025-03-30 16:52:10.676783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c5de272a73'
down_revision = '2822e0b9b0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_privilege', schema=None) as batch_op:
        batch_op.drop_constraint('admin_privilege_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint('audit_log_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('class_subject', schema=None) as batch_op:
        batch_op.drop_constraint('class_subject_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('class_subject_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('class_teacher', schema=None) as batch_op:
        batch_op.drop_constraint('class_teacher_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('fk_class_teacher_session_id', type_='foreignkey')
        batch_op.drop_constraint('class_teacher_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'session', ['session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fee_payment', schema=None) as batch_op:
        batch_op.drop_constraint('fee_payment_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('fee_payment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'session', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint('fk_result_student_id', type_='foreignkey')
        batch_op.drop_constraint('fk_result_class_id_new', type_='foreignkey')
        batch_op.drop_constraint('fk_result_session_id_new', type_='foreignkey')
        batch_op.drop_constraint('fk_result_subject_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'session', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'subject', ['subject_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('student_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_class_history', schema=None) as batch_op:
        batch_op.drop_constraint('student_class_history_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('student_class_history_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('student_class_history_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'session', ['session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_term_summary', schema=None) as batch_op:
        batch_op.drop_constraint('student_term_summary_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('student_term_summary_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('student_term_summary_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'session', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint('teacher_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('teacher_subject', schema=None) as batch_op:
        batch_op.drop_constraint('teacher_subject_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('teacher_subject_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'subject', ['subject_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_session_preference', schema=None) as batch_op:
        batch_op.drop_constraint('user_session_preference_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('user_session_preference_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'session', ['session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session_preference', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_session_preference_ibfk_1', 'session', ['session_id'], ['id'])
        batch_op.create_foreign_key('user_session_preference_ibfk_2', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('teacher_subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teacher_subject_ibfk_2', 'teacher', ['teacher_id'], ['id'])
        batch_op.create_foreign_key('teacher_subject_ibfk_1', 'subject', ['subject_id'], ['id'])

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teacher_ibfk_1', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('student_term_summary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_term_summary_ibfk_2', 'session', ['session_id'], ['id'])
        batch_op.create_foreign_key('student_term_summary_ibfk_3', 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key('student_term_summary_ibfk_1', 'classes', ['class_id'], ['id'])

    with op.batch_alter_table('student_class_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_class_history_ibfk_1', 'session', ['session_id'], ['id'])
        batch_op.create_foreign_key('student_class_history_ibfk_2', 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key('student_class_history_ibfk_3', 'classes', ['class_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_ibfk_1', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_result_subject_id', 'subject', ['subject_id'], ['id'])
        batch_op.create_foreign_key('fk_result_session_id_new', 'session', ['session_id'], ['id'])
        batch_op.create_foreign_key('fk_result_class_id_new', 'classes', ['class_id'], ['id'])
        batch_op.create_foreign_key('fk_result_student_id', 'student', ['student_id'], ['id'])

    with op.batch_alter_table('fee_payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fee_payment_ibfk_2', 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key('fee_payment_ibfk_1', 'session', ['session_id'], ['id'])

    with op.batch_alter_table('class_teacher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('class_teacher_ibfk_1', 'classes', ['class_id'], ['id'])
        batch_op.create_foreign_key('fk_class_teacher_session_id', 'session', ['session_id'], ['id'])
        batch_op.create_foreign_key('class_teacher_ibfk_2', 'teacher', ['teacher_id'], ['id'])

    with op.batch_alter_table('class_subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('class_subject_ibfk_1', 'classes', ['class_id'], ['id'])
        batch_op.create_foreign_key('class_subject_ibfk_2', 'subject', ['subject_id'], ['id'])

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('audit_log_ibfk_1', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('admin_privilege', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admin_privilege_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
