"""Reverting changes

Revision ID: d9a183a837de
Revises: b754c8c1f822
Create Date: 2024-05-19 00:24:53.218321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a183a837de'
down_revision = 'b754c8c1f822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('parent_phone_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('parent_occupation', sa.String(length=100), nullable=False),
    sa.Column('entry_class', sa.String(length=50), nullable=False),
    sa.Column('previous_class', sa.String(length=50), nullable=True),
    sa.Column('state_of_origin', sa.String(length=50), nullable=False),
    sa.Column('local_government_area', sa.String(length=50), nullable=False),
    sa.Column('religion', sa.String(length=50), nullable=False),
    sa.Column('date_registered', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
