"""Add section to Teacher

Revision ID: fe90863c941d
Revises: 14a6443c2c69
Create Date: 2025-03-03 17:59:04.443711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe90863c941d'
down_revision = '14a6443c2c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('student_class_history', schema=None) as batch_op:
    #     batch_op.drop_index('idx_student_session')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('section')

    with op.batch_alter_table('student_class_history', schema=None) as batch_op:
        batch_op.create_index('idx_student_session', ['student_id', 'session_id'], unique=False)

    # ### end Alembic commands ###
